from __future__ import annotations

from src.data.modality_signal_schema import (
    Modality,
    ModalitySignal,
    SignalStatus,
)
from src.models.prediction_service import (
    PredictionService,
    PredictionServiceError,
)


class TextSignalAdapter:
    """
    Converts the existing text prediction service output
    into the common ModalitySignal format.

    Research-only.
    This adapter does not create a clinical diagnosis
    or clinical probability.
    """

    def __init__(
        self,
        prediction_service: PredictionService | None = None,
    ) -> None:

        self.prediction_service = (
            prediction_service
            if prediction_service is not None
            else PredictionService()
        )

    def predict(
        self,
        text: str,
        subject_id: str,
        engineered_features=None,
    ) -> ModalitySignal:
        """
        Generate a standardized text modality signal.
        """

        if not isinstance(text, str):
            raise PredictionServiceError(
                "text must be a string."
            )

        if not text.strip():
            raise PredictionServiceError(
                "text cannot be empty."
            )

        if not subject_id.strip():
            raise PredictionServiceError(
                "subject_id cannot be empty."
            )

        # The current combined text model requires
        # engineered features.
        if engineered_features is None:
            return ModalitySignal(
                modality=Modality.TEXT,
                model_version=(
                    self.prediction_service.model_version
                ),
                score=None,
                status=SignalStatus.INSUFFICIENT,
                data_quality="insufficient",
                evidence=[],
                limitations=[
                    (
                        "The current text model requires "
                        "engineered features."
                    ),
                    (
                        "A text-only signal cannot be "
                        "generated by the current combined model."
                    ),
                    (
                        "This is a research-only signal, "
                        "not a clinical diagnosis."
                    ),
                ],
            )

        # Run the existing prediction service.
        result = self.prediction_service.predict_text(
            text=text,
            subject_id=subject_id,
            engineered_features=engineered_features,
            available_modalities=["text"],
            missing_modalities=["voice", "behavior"],
        )

        return ModalitySignal(
            modality=Modality.TEXT,
            model_version=result.model_version,
            score=result.model_score,
            status=SignalStatus.AVAILABLE,
            data_quality=result.data_quality.value,
            evidence=result.contributing_evidence,
            limitations=[
                (
                    "Research-only model-generated signal."
                ),
                (
                    "The score is not a clinical probability."
                ),
                (
                    "The current model requires both text "
                    "and engineered features."
                ),
            ],
        )